In [4]:
# Write a python program for addition,subtraction and multiplication (dot product and element) of matirx

# matrix multiplication
class array:
    def __init__(self,lst):
        self.lst = lst
    def reshape(self,m,n):
        M = []
        tmp = []
        for i in self.lst:
            tmp.append(i)
            if len(tmp)== n:
                M.append(tmp)
                tmp = []
        self.lst = M
    def __add__(self,other):
        row = len(self.lst)
        col = len(self.lst[0])
        M = [[0 for _ in range(col)] for _ in range(row)]
        for i in range(row):
            for j in range(col):
                M[i][j]= self.lst[i][j] + other.lst[i][j]
            return array(M)


    def disp_matrix(self):
        for i in self.lst:
            print(*i)


# raw error
lst1 = list(map(int,input().split()))
r1, c1 = list(map(int,input().split()))
arr1 = array(lst1)
arr1.reshape(r1,c1)
print("\n Matrix 1")
arr1.disp_matrix()

lst2 = list(map(int,input().split()))
r2, c2 = list(map(int,input().split()))
arr2 = array(lst2)
arr2.reshape(r2,c2)
print("\n Matrix 2")
arr2.disp_matrix()

if (r1,c1) ==(r2,c2):
    print("\n Addition")
    addition = arr1 + arr2


else:
    print("Invalid Dimensions for operation")

ValueError: too many values to unpack (expected 2)

In [ ]:
import numpy as np
lst = list (map(int,input().split()))
arr = np.array(lst).reshape((3,3))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#task 4
import numpy as np
arr1 = list(map(int, input().split()))
arr2 = list(map(int, input().split()))
r, c = list(map(int, input().split()))
print('array1:', arr1)
print('array2:', arr2)
m1= np.array(arr1).reshape(r, c)
m2= np.array(arr2).reshape(r, c)
addition = np.add(m1, m2)
substration = np.subtract(m1, m2)
multip = np.multiply(m1, m2)
div = np.floor_divide(m1, m2)
mod= np.mod(m1, m2)
power = np.power(m1,m2)
print(addition)
print(substration)
print(multip)
print(div)
print(mod)
print(power)

array1: [1, 2, 3, 4]
array2: [5, 6, 7, 8]
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [6]:
import numpy as np
arr1 = list(map(int, input().split()))
r, c = list(map(int, input().split()))
print('array1:', arr1)
m1= np.array(arr1).reshape(r, c)
tran= np.transpose(m1)
print(tran)

array1: [2, 3, 4, 5]
[[2 4]
 [3 5]]


In [9]:
import numpy as np

r, c = list(map(int, input().split()))
lst =[]
for i in r:
    x = list(map(int, input().split()))
    for j in x:
        lst.append(j)

m1= np.array(arr1).reshape(r, c)
flat = np.array(lst)
print(m1)
print(flat)

TypeError: 'int' object is not iterable