In [4]:
# array nadmin

import numpy as np 

arr = np.array([3,4,53636776,{'hello' : 123},5,"hello"])
print(arr)
print(arr.dtype)
print(type(arr))

[3 4 53636776 {'hello': 123} 5 'hello']
object
<class 'numpy.ndarray'>


In [5]:

import numpy as np 
# for boolean and intergers and float we will get unique type fpr others we will get object 
arr = np.array({'a':12 ,'b':123})
print(arr)
print(arr.dtype)
print(type(arr))

{'a': 12, 'b': 123}
object
<class 'numpy.ndarray'>


In [7]:
# ndarray operations 

arr = np.arange(1,13).reshape(3,4)
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
# Sum
out = np.sum(arr) 
print(out)

78


In [11]:
# adding along with rows
# Sum
out = np.sum(arr ,axis =0) # axis 0 adds vertically ie [1,5,9] .. [2,6,10] .. remaining
print(out)

[10 26 42]


In [ ]:
out = np.sum(arr ,axis = 1) # axis 1 adds horizontally ie [1,2,3,4] than [5,6,7,8] and other 
print(out)

In [12]:
out = np.max(arr ,axis =0) # gives max of column
print(out)

[ 9 10 11 12]


In [13]:
out = np.max(arr ,axis = 1) # gives max of row
print(out)

[ 4  8 12]


In [21]:
a = 4.5
out = round(a) # rounds off the value if the no. is odd , for even it gives the same integer
print(out)

4


In [22]:
a = np.array([3.5,2.33,1.009])
out = np.round(a,1) # we dont get 0 as output after the decimal point
print(out)

[3.5 2.3 1. ]


In [25]:
a = np.array([-3.5,2.33,1.009])
out = np.floor(a)
print(out)

[-4.  2.  1.]


In [26]:
a = np.array([-3.5,2.33,1.009])
out = np.ceil(a)
print(out)

[-3.  3.  2.]


In [28]:
print(np.zeros((3,3))) # it gives in string format  and gives a matrix of given dimensions with 0s

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
(np.zeros((3,3))) # representation gives in array format  and gives a matrix of given dimensions with 0s

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
print(np.empty((32,3))) # it gives random matrix of given dimensions

[[4.99006302e-322 0.00000000e+000 4.94065646e-324]
 [2.12199587e-314 0.00000000e+000 4.94065646e-324]
 [5.08887615e-322 0.00000000e+000 4.94065646e-324]
 [4.94065646e-322 0.00000000e+000 4.94065646e-324]
 [2.12199587e-314 0.00000000e+000 4.94065646e-324]
 [2.12199587e-314 0.00000000e+000 4.94065646e-324]
 [4.24399163e-314 0.00000000e+000 4.94065646e-324]
 [4.99006302e-322 0.00000000e+000 9.88131292e-324]
 [6.36598745e-314 0.00000000e+000 9.88131292e-324]
 [4.24399163e-314 0.00000000e+000 9.88131292e-324]
 [2.12199587e-314 0.00000000e+000 9.88131292e-324]
 [8.48798321e-314 0.00000000e+000 9.88131292e-324]
 [1.06099790e-313 0.00000000e+000 1.48219694e-323]
 [8.48798321e-314 0.00000000e+000 1.48219694e-323]
 [2.12199586e-314 0.00000000e+000 1.48219694e-323]
 [4.94065646e-324 0.00000000e+000 1.48219694e-323]
 [2.12199584e-314 0.00000000e+000 1.48219694e-323]
 [4.10074486e-322 0.00000000e+000 1.48219694e-323]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+0

In [4]:
import numpy as np
arr = np.zeros((4, 3 ,2), dtype=int)          #3D array with zeros of the specified shape
rnd_arr = np.random.randint(0, 20, (4, 3 ,2)) #3D array with random integers from 0 to 20

print(arr)

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


In [1]:
import numpy as np
print(np.zeros((3,4),dtype = int))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
# it gives the starting and ending values as specified with a total of the n numebrs given at the end 
arr = np.linspace(1,10,13) 
print(arr)

[ 1.    1.75  2.5   3.25  4.    4.75  5.5   6.25  7.    7.75  8.5   9.25
 10.  ]
