In [18]:
import numpy as np
val = np.array([[1,2],[3,4],[5,6]])
print(f"Before Reshaping:\n{val}")
val.shape = (2,3)
print(f"After Reshaping:\n{val}")

Before Reshaping:
[[1 2]
 [3 4]
 [5 6]]
After Reshaping:
[[1 2 3]
 [4 5 6]]


: 